package st

// This file implements the interactive widgets. Every widget follows the same
// pattern that gives Streamlit its feel:
//
//  1. Resolve a stable key (caller-supplied or auto-generated by call order).
//  2. Read the widget's current value from persisted session state, falling
//     back to the supplied default on the first run.
//  3. Append a keyed element describing the widget and its current value.
//  4. Return the current value to the app code.
//
// When the user interacts with a widget the frontend posts a {key, value}
// event; the server records it in the session's widget map and reruns the app,
// so step 2 above returns the updated value on the next run.

// Button adds a clickable button and returns true on the single run triggered
// by a click. An optional stable key may be supplied as the final argument.
func (c *Container) Button(label string, key ...string) bool {
	k := c.s.key(optKey(key), "button")
	clicked := c.s.clicked[k]
	c.addWidget(k, "button", props{"label": label})
	return clicked
}

// Checkbox adds a checkbox initialised to def and returns its current state.
func (c *Container) Checkbox(label string, def bool, key ...string) bool {
	k := c.s.key(optKey(key), "checkbox")
	val := asBool(c.s.widgets[k], def)
	c.addWidget(k, "checkbox", props{"label": label, "value": val})
	return val
}

// Slider adds a numeric slider bounded by min and max, initialised to def, and
// returns its current value. step controls the increment; if step is zero a
// sensible default of (max-min)/100 is used. The returned value is clamped to
// the slider's range.
func (c *Container) Slider(label string, min, max, def, step float64, key ...string) float64 {
	k := c.s.key(optKey(key), "slider")
	if step <= 0 {
		if max > min {
			step = (max - min) / 100
		} else {
			step = 1
		}
	}
	val := clampFloat(asFloat(c.s.widgets[k], def), min, max)
	c.addWidget(k, "slider", props{
		"label": label, "min": min, "max": max, "value": val, "step": step,
	})
	return val
}

// NumberInput adds a numeric entry field initialised to def and returns its
// current value.
func (c *Container) NumberInput(label string, def float64, key ...string) float64 {
	k := c.s.key(optKey(key), "number")
	val := asFloat(c.s.widgets[k], def)
	c.addWidget(k, "number", props{"label": label, "value": val})
	return val
}

// TextInput adds a single-line text field initialised to def and returns its
// current value.
func (c *Container) TextInput(label, def string, key ...string) string {
	k := c.s.key(optKey(key), "text_input")
	val := asString(c.s.widgets[k], def)
	c.addWidget(k, "text_input", props{"label": label, "value": val})
	return val
}

// TextArea adds a multi-line text field initialised to def and returns its
// current value.
func (c *Container) TextArea(label, def string, key ...string) string {
	k := c.s.key(optKey(key), "text_area")
	val := asString(c.s.widgets[k], def)
	c.addWidget(k, "text_area", props{"label": label, "value": val})
	return val
}

// SelectBox adds a drop-down of options and returns the selected option. The
// first option is selected by default; if options is empty the empty string is
// returned.
func (c *Container) SelectBox(label string, options []string, key ...string) string {
	k := c.s.key(optKey(key), "selectbox")
	def := ""
	if len(options) > 0 {
		def = options[0]
	}
	val := asString(c.s.widgets[k], def)
	if !containsString(options, val) {
		val = def
	}
	c.addWidget(k, "selectbox", props{"label": label, "options": options, "value": val})
	return val
}

// Radio adds a group of mutually exclusive radio options and returns the
// selected option. Behaves like [Container.SelectBox] for defaults.
func (c *Container) Radio(label string, options []string, key ...string) string {
	k := c.s.key(optKey(key), "radio")
	def := ""
	if len(options) > 0 {
		def = options[0]
	}
	val := asString(c.s.widgets[k], def)
	if !containsString(options, val) {
		val = def
	}
	c.addWidget(k, "radio", props{"label": label, "options": options, "value": val})
	return val
}

// MultiSelect adds a multiple-selection control and returns the currently
// selected options. Selections not present in options are dropped.
func (c *Container) MultiSelect(label string, options []string, key ...string) []string {
	k := c.s.key(optKey(key), "multiselect")
	sel := asStringSlice(c.s.widgets[k], nil)
	filtered := make([]string, 0, len(sel))
	for _, s := range sel {
		if containsString(options, s) {
			filtered = append(filtered, s)
		}
	}
	c.addWidget(k, "multiselect", props{"label": label, "options": options, "value": filtered})
	return filtered
}
